</$objtype/mkfile

# T1 unit tests.  Each test is a self-contained program that exits
# non-zero and prints a one-line "FAIL: reason" when it fails.  To
# add one: write foo.c here and add foo to TESTS.
TESTS=\
	csumtest\
	structtest\
	geomtest\
	devtest\
	supertest\
	montest\
	fmtcktest\
	storetest\
	objtest\
	scrubtest\
	committest\
	enumtest\
	maptest\
	bmrebuildtest\
	peeropstest\
	srvtest\
	srvenumtest\
	srviotest\
	srvwiretest\
	maphandletest\
	montreetest\

LIB=../lib/libshoal.a$O
SRVLIB=../srv/libshoalsrv.a$O
MONLIB=../mon/libshoalmon.a$O
HFILES=../lib/shoal.h ../lib/store.h t1.h
LDFLAGS=

PROGS=${TESTS:%=$O.%}

default:V:	all

all:V:	$PROGS

$O.%:	%.$O $LIB
	$LD $LDFLAGS -o $target $prereq

# The six programs that drive a 9P surface link a server library too
# and are libthread programs; every other test's link line is
# unchanged.
$O.srvtest:	srvtest.$O $SRVLIB $LIB
	$LD $LDFLAGS -o $target $prereq

srvtest.$O:	srvtest.c srv9p.h ../srv/srv.h $HFILES
	$CC $CFLAGS srvtest.c

$O.srvenumtest:	srvenumtest.$O $SRVLIB $LIB
	$LD $LDFLAGS -o $target $prereq

srvenumtest.$O:	srvenumtest.c srv9p.h ../srv/srv.h $HFILES
	$CC $CFLAGS srvenumtest.c

$O.srviotest:	srviotest.$O $SRVLIB $LIB
	$LD $LDFLAGS -o $target $prereq

srviotest.$O:	srviotest.c srv9p.h ../srv/srv.h $HFILES
	$CC $CFLAGS srviotest.c

$O.srvwiretest:	srvwiretest.$O $SRVLIB $LIB
	$LD $LDFLAGS -o $target $prereq

srvwiretest.$O:	srvwiretest.c srv9p.h ../srv/srv.h $HFILES
	$CC $CFLAGS srvwiretest.c

$O.maphandletest:	maphandletest.$O $SRVLIB $LIB
	$LD $LDFLAGS -o $target $prereq

maphandletest.$O:	maphandletest.c srv9p.h ../srv/srv.h $HFILES
	$CC $CFLAGS maphandletest.c

# The monitor's 9P surface links the monitor library instead, and its
# in-process client is test/mon9p.h.
$O.montreetest:	montreetest.$O $MONLIB $LIB
	$LD $LDFLAGS -o $target $prereq

montreetest.$O:	montreetest.c mon9p.h ../mon/mon.h $HFILES
	$CC $CFLAGS montreetest.c

%.$O:	%.c $HFILES
	$CC $CFLAGS $stem.c

test:V:	$PROGS
	for(t in $PROGS){
		echo '	'^$t
		./$t || exit 'test failed'
	}

clean nuke:V:
	rm -f *.[$OS] [$OS].* $CLEANFILES
